// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

type Calendar struct {
	ID     string
	UserID interface{}
	Name   string
	Color  string
}

type Event struct {
	ID          string
	CalendarID  interface{}
	Title       string
	Description sql.NullString
	StartTime   interface{}
	EndTime     interface{}
	Location    sql.NullString
}

type User struct {
	ID       string
	Username string
	Password string
}
