// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"
)

const createCalendar = `-- name: CreateCalendar :one
INSERT INTO calendars (
  id, user_id, name, color
) VALUES (
    ?, ?, ?, ?
) RETURNING id, user_id, name, color
`

type CreateCalendarParams struct {
	ID     string
	UserID interface{}
	Name   string
	Color  string
}

func (q *Queries) CreateCalendar(ctx context.Context, arg CreateCalendarParams) (Calendar, error) {
	row := q.db.QueryRowContext(ctx, createCalendar,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Color,
	)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id, username, password
) VALUES (
  ?, ?, ?
) RETURNING id, username, password
`

type CreateUserParams struct {
	ID       string
	Username string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Username, arg.Password)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}

const getCalendarsByUserID = `-- name: GetCalendarsByUserID :many
SELECT id, user_id, name, color FROM calendars WHERE user_id = ?
`

func (q *Queries) GetCalendarsByUserID(ctx context.Context, userID interface{}) ([]Calendar, error) {
	rows, err := q.db.QueryContext(ctx, getCalendarsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calendar
	for rows.Next() {
		var i Calendar
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}
